export const siteConfig = {
  business: {
    name: "Final Touch Landscaping",
    email: "Finaltouchlandscaping75@gmail.com",
    phone: "(618) 308-1119",
    address: "1710 Akin Road, Van Nuys, CA 91405",
    serviceArea: "Van Nuys, CA and surrounding areas",
  },
  social: {
    facebook: "https://www.facebook.com/finaltouchlandscaping",
    instagram: "https://www.instagram.com/finaltouchlandscaping",
    whatsapp: "https://wa.me/16183081119",
  },
  hours: {
    monday: "7:00 AM - 6:00 PM",
    tuesday: "7:00 AM - 6:00 PM",
    wednesday: "7:00 AM - 6:00 PM",
    thursday: "7:00 AM - 6:00 PM",
    friday: "7:00 AM - 6:00 PM",
    saturday: "8:00 AM - 4:00 PM",
    sunday: "Closed",
  },
  services: [
    {
      id: "lawn-maintenance",
      name: "Lawn Maintenance",
      description: "Regular lawn care including mowing, edging, and seasonal treatments",
      icon: "🌱",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=300&fit=crop",
    },
    {
      id: "landscape-design",
      name: "Landscape Design",
      description: "Custom landscape design and installation for residential properties",
      icon: "🎨",
      image: "https://images.unsplash.com/photo-1585320806997-c33953f03a98?w=500&h=300&fit=crop",
    },
    {
      id: "hardscaping",
      name: "Hardscaping",
      description: "Patios, walkways, retaining walls, and other hardscape features",
      icon: "🏗️",
      image: "https://images.unsplash.com/photo-1569829221549-82b7c4e3a6e9?w=500&h=300&fit=crop",
    },
    {
      id: "tree-care",
      name: "Tree & Shrub Care",
      description: "Professional tree trimming, pruning, and shrub maintenance",
      icon: "🌳",
      image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&h=300&fit=crop",
    },
    {
      id: "seasonal-cleanup",
      name: "Seasonal Cleanups",
      description: "Spring and fall cleanups to keep your property looking pristine",
      icon: "🍂",
      image: "https://images.unsplash.com/photo-1559033615-cd4628902d4a?w=500&h=300&fit=crop",
    },
    {
      id: "irrigation",
      name: "Irrigation Setup",
      description: "Professional irrigation system installation and maintenance",
      icon: "💧",
      image: "https://images.unsplash.com/photo-1595488888651-3b47e7e52e4f?w=500&h=300&fit=crop",
    },
    {
      id: "mulching",
      name: "Mulching",
      description: "Quality mulch installation for landscaping beds",
      icon: "🪵",
      image: "https://images.unsplash.com/photo-1557804506-669714d2e9d8?w=500&h=300&fit=crop",
    },
    {
      id: "snow-removal",
      name: "Snow & Ice Services",
      description: "Winter snow removal and ice management services",
      icon: "❄️",
      image: "https://images.unsplash.com/photo-1518098268026-4e89f1a2c008?w=500&h=300&fit=crop",
    },
  ],
  stats: {
    yearsExperience: 15,
    projectsCompleted: 500,
    clientsSatisfied: 1200,
    teamMembers: 25,
  },
}
